# Generated by Django 4.0.3 on 2022-07-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='index',
        ),
    ]
