# Generated by Django 4.0.3 on 2022-07-30 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contact_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='contact',
        ),
    ]
